language: python
python:
- '2.7'
install:
- pip install coverage
- pip install coveralls
- ./install_deps
script: coverage run ./manage.py test
after_success: coveralls
deploy:
  provider: gae
  keyfile: 'potaticket-05e85f74d78e.json'
  project: potaticket
  default: true
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_3bc4669386f9_key -iv $encrypted_3bc4669386f9_iv
  -in potaticket-05e85f74d78e.json.enc -out potaticket-05e85f74d78e.json
  -d
