language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install coverage"
  - "pip install coveralls"
  - "./install_deps"
# command to run tests
script: coverage run ./manage.py test
after_success: coveralls

deploy:
  provider: gae
  keyfile: ""
  project: "potaticket"
